# See: https://packaging.python.org/guides/supporting-windows-using-appveyor/
environment:
  matrix:
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"

# See: https://help.appveyor.com/discussions/problems/12705-custom-build-script-script-mode
build: off

install:
  - "%PYTHON%\\python.exe -m pip install -U pip"
  - "%PYTHON%\\python.exe -m pip install -U --force-reinstall setuptools tox"

test_script:
  - "%PYTHON%\\python.exe -m tox -e py,integration"
