# Configuration for AppVeyor builds

branches:
  except:
    - master

only_commits:
  message: Trigger CI

environment:
  # Appveyor machines come with miniconda already installed.
  CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\continuous-integration\\appveyor\\run_with_env.cmd"
  matrix:
    - TARGET_ARCH: "x64"
      PYTHON_BUILD_RESTRICTIONS: "3.7*"
      CONDA_PY: "37"
      CONDA_INSTALL_LOCN: "C:\\Miniconda37-x64"

# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

# See: https://help.appveyor.com/discussions/problems/12705-custom-build-script-script-mode
build: off

install:
  # No need to install miniconda because appveyor comes with it.
  - cmd: SET PATH=%CONDA_INSTALL_LOCN%;%CONDA_INSTALL_LOCN%\Scripts;%PATH%
  # Check that we have the expected version and architecture for Python
  - cmd: python --version
  - cmd: conda info
  - cmd: conda config --set always_yes true
  - cmd: conda install pip setuptools wheel pytest sqlite
  - cmd: conda update --quiet conda
  - cmd: conda install pytorch torchvision cudatoolkit=10.2 -c pytorch
  - cmd: pip install -e .[mlflow,wandb]

test_script:
  # We have to activate the conda environment explicitly
  - activate
  - pytest --durations=20 tests -m "not slow"
  - pytest --durations=20 tests -m slow

# References:
# 1. https://github.com/astropy/conda-build-tools/blob/master/appveyor.yml
