# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
# cf. https://github.com/astral-sh/ruff-pre-commit
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.9
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
# cf. https://github.com/sphinx-contrib/sphinx-lint
- repo: https://github.com/sphinx-contrib/sphinx-lint
  rev: v1.0.2
  hooks:
    - id: sphinx-lint
      files: ^docs/
# cf. https://github.com/LilSpazJoekp/docstrfmt
- repo: https://github.com/LilSpazJoekp/docstrfmt
  rev: v2.2.0
  hooks:
    - id: docstrfmt
      args: [ --line-length, "120", --preserve-adornments, --no-docstring-trailing-line ]
      types: [ rst ]
      files: ^docs/
