"""Configuration file for the Sphinx documentation builder.

This file does only contain a selection of the most common options. For a full list see the documentation:
http://www.sphinx-doc.org/en/master/config

-- Path setup --------------------------------------------------------------

If extensions (or modules to document with autodoc) are in another directory, add these directories to sys.path here. If
the directory is relative to the documentation root, use os.path.abspath to make it absolute, like shown here.
"""

import os
import re
import sys
from datetime import date

sys.path.insert(0, os.path.abspath("../../src"))
# sys.path.insert(0, os.path.abspath('..'))

# -- Mockup PyTorch to exclude it while compiling the docs--------------------
# autodoc_mock_imports = ['torch', 'torchvision']

# from unittest.mock import Mock
# sys.modules['numpy'] = Mock()
# sys.modules['numpy.linalg'] = Mock()
# sys.modules['scipy'] = Mock()
# sys.modules['scipy.optimize'] = Mock()
# sys.modules['scipy.interpolate'] = Mock()
# sys.modules['scipy.sparse'] = Mock()
# sys.modules['scipy.ndimage'] = Mock()
# sys.modules['scipy.ndimage.filters'] = Mock()
# sys.modules['tensorflow'] = Mock()
# sys.modules['theano'] = Mock()
# sys.modules['theano.tensor'] = Mock()
# sys.modules['torch'] = Mock()
# sys.modules['torch.optim'] = Mock()
# sys.modules['torch.nn'] = Mock()
# sys.modules['torch.nn.init'] = Mock()
# sys.modules['torch.autograd'] = Mock()
# sys.modules['sklearn'] = Mock()
# sys.modules['sklearn.model_selection'] = Mock()
# sys.modules['sklearn.utils'] = Mock()

# -- Project information -----------------------------------------------------

project = "pykeen"
copyright = f"2019-{date.today().year}, PyKEEN Project Team"  # noqa: A001
author = "PyKEEN Project Team"

# The full version, including alpha/beta/rc tags.
release = "1.11.2-dev"

# The short X.Y version.
parsed_version = re.match(
    r"(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(?:-(?P<release>[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+(?P<build>[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?",
    release,
)
version = parsed_version.expand(r"\g<major>.\g<minor>.\g<patch>")

if parsed_version.group("release"):
    tags.add("prerelease")  # noqa:F821

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
add_module_names = False

# A list of prefixes that are ignored when creating the module index. (new in Sphinx 0.6)
modindex_common_prefix = ["pykeen."]

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autosummary",
    "sphinx.ext.autodoc",
    "sphinx.ext.coverage",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.mathjax",
    "sphinx.ext.viewcode",
    "sphinx_click.ext",
    "sphinx_automodapi.automodapi",
    "texext",
]

# show todo's
todo_include_todos = True

# generate autosummary pages
autosummary_generate = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = {".rst": "restructuredtext"}

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#
html_logo = "logo.png"

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "PyKEENdoc"

# -- Options for LaTeX output ------------------------------------------------

# latex_elements = {
#     The paper size ('letterpaper' or 'a4paper').
#
#     'papersize': 'letterpaper',
#
#     The font size ('10pt', '11pt' or '12pt').
#
#     'pointsize': '10pt',
#
#     Additional stuff for the LaTeX preamble.
#
#     'preamble': '',
#
#     Latex figure (float) alignment
#
#     'figure_align': 'htbp',
# }

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
# latex_documents = [
#     (
#         master_doc,
#         'pykeen.tex',
#         'PyKEEN Documentation',
#         author,
#         'manual',
#     ),
# ]

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (
        master_doc,
        "pykeen",
        "PyKEEN Documentation",
        [author],
        1,
    ),
]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "pykeen",
        "PyKEEN Documentation",
        author,
        "PyKEEN Project Team",
        "Training and evaluation knowledge graph embedding models.",
        "Miscellaneous",
    ),
]

# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
# epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
# epub_exclude_files = ['search.html']

# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "torch": ("https://pytorch.org/docs/stable", None),
    "torchvision": ("https://pytorch.org/vision/stable", None),
    "torch_geometric": ("https://pytorch-geometric.readthedocs.io/en/latest", None),
    "numpy": ("https://numpy.org/doc/stable", None),
    "optuna": ("https://optuna.readthedocs.io/en/latest", None),
    "pybel": ("https://pybel.readthedocs.io/en/latest", None),
    "pyobo": ("https://pyobo.readthedocs.io/en/stable", None),
    "class_resolver": ("https://class-resolver.readthedocs.io/en/latest", None),
    "bio2bel": ("https://bio2bel.readthedocs.io/en/latest", None),
    "boto3": ("https://boto3.amazonaws.com/v1/documentation/api/latest", None),
    "sklearn": ("https://scikit-learn.org/stable", None),
    "scipy": ("https://docs.scipy.org/doc/scipy", None),
    "datasets": ("https://huggingface.co/docs/datasets/main/en", None),
    "transformers": ("https://huggingface.co/docs/transformers/main/en", None),
    "pandas": ("https://pandas.pydata.org/docs", None),
    "pystow": ("https://pystow.readthedocs.io/en/latest", None),
    "IPython": ("https://ipython.readthedocs.io/en/stable", None),
    "torch_ppr": ("https://torch-ppr.readthedocs.io/en/latest", None),
}

autoclass_content = "both"
# autodoc_member_order = 'bysource'
autodoc_typehints = "both"
# autodoc_preserve_defaults = True

# Output SVG inheritance diagrams
graphviz_output_format = "svg"

# -- Nitpicky mode exceptions -------------------------------------------------
#
# These are all cases where the referenced object genuinely exists in the codebase, but Sphinx has no way to
# generate (or reach) an anchor for it, so a cross-reference to it can never resolve. They fall into a few
# structural buckets:

nitpick_ignore_regex = [
    # `__init__`/`__repr__`/`extra_repr` are folded into their class' docs via `autoclass_content = "both"`, so
    # autodoc never generates a separate, individually-linkable anchor for them.
    (r"py:(meth|func)", r"(.*\.)?__init__$"),
    (r"py:(meth|func)", r"(.*\.)?__repr__$"),
    (r"py:(meth|func)", r"(.*\.)?extra_repr$"),
    # `class_resolver`-based singleton resolver instances (`*_resolver`) report their `__module__` as
    # `class_resolver.api`, not the pykeen module they are instantiated in, so autodoc can't anchor them there.
    (r"py:(data|const)", r".*_resolver$"),
    (r"py:meth", r".*_resolver\.make(_many)?$"),
    # Generic aliases render their type parameters inline (e.g. `collections.abc.Mapping[str, ...]`), which
    # never matches a plain `nitpick_ignore` string; match on the unparameterized prefix instead.
    (r"py:class", r"collections\.abc\.Mapping\[.*"),
    (r"py:class", r"class_resolver\.func\.FunctionResolver\[.*"),
]

nitpick_ignore = [
    # `pykeen.lr_schedulers.LRScheduler` is a direct re-export of `torch.optim.lr_scheduler.LRScheduler`
    # (`src/pykeen/lr_schedulers/__init__.py`), so automodapi pulls in torch's own method docstrings. Those
    # reference targets are broken in torch's own docs (version-dependent) and outside pykeen's control.
    ("py:attr", "torch.optim.Optimizer.param_groups"),
    ("py:attr", "last_epoch"),
    ("py:meth", "_get_closed_form_lr"),
    # TypeVars and type aliases: Sphinx cannot resolve these as `py:class`/`py:obj` targets unless each is
    # individually documented, which none of these (from `pykeen.typing`, `pykeen.utils`, or re-exported from
    # `class_resolver`) are.
    ("py:class", "AdditionalFilterTriplesHint"),
    ("py:class", "BatchNorm"),
    ("py:class", "Clamp"),
    ("py:class", "Dropout"),
    ("py:class", "EdgeWeighting"),
    ("py:class", "FloatTensor"),
    ("py:class", "Hint"),
    ("py:class", "HintOrType"),
    ("py:class", "LongTensor"),
    ("py:class", "LookupOrType"),
    ("py:class", "MappedTriples"),
    ("py:class", "MarginRankingLoss"),
    ("py:class", "OneOrManyHintOrType"),
    ("py:class", "OneOrManyOptionalKwargs"),
    ("py:class", "OneOrSequence"),
    ("py:class", "Optimizer"),
    ("py:class", "OptionalKwargs"),
    ("py:class", "Representation"),
    ("py:class", "TargetHint"),
    ("py:class", "TrainingCallbackKwargsHint"),
    ("py:class", "X"),
    ("py:class", "class_resolver"),
    ("py:class", "class_resolver.func.FunctionResolver"),
    ("py:class", "class_resolver.utils.X"),
    ("py:class", "collections.abc.Mapping"),
    ("py:class", "dataclasses.dataclass"),
    ("py:class", "pykeen.datasets.ea.combination.FactoryType"),
    ("py:class", "pykeen.evaluation.evaluation_loop.BatchType"),
    ("py:class", "pykeen.evaluation.evaluator.MetricKeyType"),
    ("py:class", "pykeen.utils.K"),
    ("py:class", "pykeen.utils.V"),
    ("py:class", "pykeen.utils.X"),
    ("py:obj", "-1"),
    ("py:obj", "pykeen.datasets.ea.combination.FactoryType"),
    ("py:obj", "pykeen.evaluation.evaluation_loop.BatchType"),
    ("py:obj", "pykeen.evaluation.evaluator.MetricKeyType"),
    ("py:obj", "pykeen.training.training_loop.BatchType"),
    ("py:obj", "pykeen.triples.instances.BatchType"),
    ("py:obj", "pykeen.typing.Representation"),
    ("py:obj", "pykeen.typing.X"),
    # Third-party types that only ever appear via rendered type hints (`autodoc_typehints = "both"`), using
    # shorthand/private paths that don't match any public, inventory-documented target.
    ("py:class", "nn.Module"),
    ("py:class", "nn.Parameter"),
    ("py:class", "np.ndarray"),
    ("py:class", "torch.FloatTensor"),
    ("py:class", "torch.LongTensor"),
    ("py:class", "torch._VariableFunctionsClass.tensor"),
    ("py:class", "torch.nn.modules.loss._Loss"),
    ("py:mod", "pykeen.nn.modules._Loss"),
    ("py:func", "np.random.seed"),
    # Third-party libraries with no reachable Sphinx inventory, or that don't document the referenced object at
    # a public path.
    ("py:class", "neptune.OfflineBackend"),
    ("py:class", "optuna.storages._base.BaseStorage"),
    ("py:class", "pandas.core.frame.DataFrame"),
    ("py:class", "pytorch_lightning.core.module.LightningModule"),
    ("py:class", "scipy.sparse.csgraph"),
    ("py:func", "opt_einsum.contract"),
    ("py:func", "torch_ppr.page_rank"),
    ("py:func", "wandb.init"),
    ("py:mod", "bio2bel.io.pykeen"),
    ("py:mod", "pystow"),
    ("py:mod", "tensorboard"),
    ("py:mod", "torch_geometric.nn.conv"),
    ("py:mod", "torch_max_mem"),
    ("py:mod", "torch_sparse"),
    ("py:mod", "torchvision.models"),
    ("py:mod", "torchvision.transforms"),
    ("py:mod", "tqdm"),
    ("py:mod", "transformers"),
    # Real, correctly-named pykeen objects that automodapi never exposes: either the referenced attribute is
    # only a bare type annotation (never a documented class-level value), the object is deliberately excluded
    # from its module's `__all__`, or its containing module is never pulled into any `automodapi::` directive.
    ("py:class", "Partition"),
    ("py:class", "pykeen.ablation.ablation.SplitToPathDict"),
    ("py:class", "pykeen.datasets.ea.base.EADataset"),
    ("py:class", "pykeen.datasets.ea.wk3l.MTransEDataset"),
    ("py:class", "pykeen.datasets.ogb.BioKGEvalDict"),
    ("py:class", "pykeen.datasets.ogb.BioKGTrainDict"),
    ("py:class", "pykeen.datasets.ogb.OGBLoader"),
    ("py:class", "pykeen.datasets.ogb.WikiKG2EvalDict"),
    ("py:class", "pykeen.datasets.ogb.WikiKG2TrainDict"),
    ("py:class", "pykeen.evaluation.classification_evaluator.ClassificationMetricKey"),
    ("py:class", "pykeen.evaluation.classification_evaluator.ScorePack"),
    ("py:class", "pykeen.evaluation.evaluation_loop.EvaluationLoop"),
    ("py:class", "pykeen.evaluation.rank_based_evaluator.RankBasedMetricKey"),
    ("py:class", "pykeen.evaluation.rank_based_evaluator.RankPack"),
    ("py:class", "pykeen.hpo.hpo.Objective"),
    ("py:class", "pykeen.metrics.ranking.MedianAbsoluteDeviation"),
    ("py:class", "pykeen.models.nbase._NewAbstractModel"),
    ("py:class", "pykeen.nn.representation.Partition"),
    ("py:class", "pykeen.nn.vision.cache.WikidataImageCache"),
    ("py:class", "pykeen.training.TrainingCallback"),
    ("py:class", "pykeen.triples.triples_factory.TripleCondenser"),
]
