"""PyKEEN internal "nn" module."""

from class_resolver import ClassResolver

from . import init
from .combination import (
    Combination,
    ComplexSeparatedCombination,
    ConcatAggregationCombination,
    ConcatCombination,
    ConcatProjectionCombination,
    GatedCombination,
)
from .message_passing import RGCNRepresentation
from .meta import FeatureEnrichedEmbedding, MLPTransformedRepresentation
from .modules import (
    AutoSFInteraction,
    BoxEInteraction,
    ComplExInteraction,
    ConvEInteraction,
    ConvKBInteraction,
    CPInteraction,
    CrossEInteraction,
    DistMAInteraction,
    DistMultInteraction,
    ERMLPEInteraction,
    ERMLPInteraction,
    HolEInteraction,
    Interaction,
    KG2EInteraction,
    LineaREInteraction,
    MonotonicAffineTransformationInteraction,
    MultiLinearTuckerInteraction,
    MuREInteraction,
    NTNInteraction,
    PairREInteraction,
    ProjEInteraction,
    QuatEInteraction,
    RESCALInteraction,
    RotatEInteraction,
    SEInteraction,
    SimplEInteraction,
    TorusEInteraction,
    TransDInteraction,
    TransEInteraction,
    TransFInteraction,
    TransformerInteraction,
    TransHInteraction,
    TransRInteraction,
    TripleREInteraction,
    TuckERInteraction,
    UMInteraction,
    interaction_resolver,
)
from .node_piece import NodePieceRepresentation, TokenizationRepresentation, tokenizer_resolver
from .pyg import (
    FeaturizedMessagePassingRepresentation,
    SimpleMessagePassingRepresentation,
    TypedMessagePassingRepresentation,
)
from .representation import (
    BackfillRepresentation,
    BiomedicalCURIERepresentation,
    CachedTextRepresentation,
    CombinedRepresentation,
    Embedding,
    EmbeddingBagRepresentation,
    LowRankRepresentation,
    MultiBackfillRepresentation,
    Partition,
    PartitionRepresentation,
    Representation,
    SingleCompGCNRepresentation,
    SubsetRepresentation,
    TensorTrainRepresentation,
    TextRepresentation,
    TransformedRepresentation,
    WikidataTextRepresentation,
)
from .vision import VisualRepresentation, WikidataVisualRepresentation

__all__ = [
    "AutoSFInteraction",
    "BackfillRepresentation",
    "BiomedicalCURIERepresentation",
    "BoxEInteraction",
    "CPInteraction",
    "Combination",
    "CombinedRepresentation",
    "ComplExInteraction",
    "ComplexSeparatedCombination",
    "ConcatAggregationCombination",
    "ConcatCombination",
    "ConcatProjectionCombination",
    "ConvEInteraction",
    "ConvKBInteraction",
    "CrossEInteraction",
    "DistMAInteraction",
    "DistMultInteraction",
    "ERMLPEInteraction",
    "ERMLPInteraction",
    "Embedding",
    "EmbeddingBagRepresentation",
    "FeatureEnrichedEmbedding",
    "FeaturizedMessagePassingRepresentation",
    "GatedCombination",
    "HolEInteraction",
    "Interaction",
    "KG2EInteraction",
    "LineaREInteraction",
    "LowRankRepresentation",
    "MLPTransformedRepresentation",
    "MonotonicAffineTransformationInteraction",
    "MuREInteraction",
    "MultiBackfillRepresentation",
    "MultiLinearTuckerInteraction",
    "NTNInteraction",
    "NodePieceRepresentation",
    "PairREInteraction",
    "Partition",
    "PartitionRepresentation",
    "ProjEInteraction",
    "QuatEInteraction",
    "RESCALInteraction",
    "RGCNRepresentation",
    "Representation",
    "RotatEInteraction",
    "SEInteraction",
    "SimplEInteraction",
    "SimpleMessagePassingRepresentation",
    "SingleCompGCNRepresentation",
    "SubsetRepresentation",
    "TensorTrainRepresentation",
    "TextRepresentation",
    "TokenizationRepresentation",
    "TorusEInteraction",
    "TransDInteraction",
    "TransEInteraction",
    "TransFInteraction",
    "TransHInteraction",
    "TransRInteraction",
    "TransformedRepresentation",
    "TransformerInteraction",
    "TripleREInteraction",
    "TuckERInteraction",
    "TypedMessagePassingRepresentation",
    "UMInteraction",
    "VisualRepresentation",
    "WikidataTextRepresentation",
    "WikidataVisualRepresentation",
    "init",
    "interaction_resolver",
    "representation_resolver",
    "tokenizer_resolver",
]

#: A resolver for representations
representation_resolver: ClassResolver[Representation] = ClassResolver.from_subclasses(
    base=Representation,  # type: ignore[type-abstract]
    default=Embedding,
    skip={
        CachedTextRepresentation,
    },
)
