name: Windows Tests

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  tests:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8 ]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          conda install pip setuptools wheel pytest sqlite
          conda install pytorch torchvision cudatoolkit=10.2 -c pytorch
          pip install -e .[mlflow,wandb]
      - name: Run fast tests
        run: pytest --durations=20 tests -m "not slow"
      - name: Run slow tests
        run: pytest --durations=20 tests -m "slow"
